language: ruby

rvm:
  - "2.0.0"
  - "2.1.3"
  - "2.2.5"
  - "2.3.1"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install gdb
  - gem install bundler

script:
  - sudo sysctl kernel.yama.ptrace_scope=0
  - bundle exec rspec spec
